apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: rds-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: petclinic/ENV/rds/master
        property: username
    - secretKey: password
      remoteRef:
        key: petclinic/ENV/rds/master
        property: password
